# SMS server options
server:
  protocol: 'http'
  host:     '0.0.0.0'
  port:     '8888'
  path:     '/enqueue'
  username: 'scc'
  password: 'admin'

# IRC options
irc:
  nick:     "svarog"
  server:   "irc.suse.de"
  channels: ["#svarog"]

# Other options
contact:
  email: happy-customer@suse.de
