# SMS server options
basic_auth:
  username: 'user'
  password: 'password'

# IRC options
irc:
  server:   <server>
  port:     <port>
  use_ssl:  false
  channels: ["#chanel"]
  nick:     "svarog"

# Mail options
contact:
  email: "email@domain.com"
