# SMS server options
basic_auth:
  username: 'user'
  password: 'password'

# IRC options
irc:
  nick:     "svarog"
  server:   "irc server hostname"
  channels: ["#irc_channel"]

# Mail options
contact:
  email: "email@domain.com"
